package xiaozhi.common.utils;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

public class AESUtilsTest {

    @Test
    public void testEncryptAndDecrypt() {
        String key = "xiaozhi1234567890";
        String plainText = "Hello, Xiaozhi!";

        System.out.println("Original text: " + plainText);
        System.out.println("Key: " + key);

        // Encrypt
        String encrypted = AESUtils.encrypt(key, plainText);
        System.out.println("Encrypted result: " + encrypted);

        // Decrypt
        String decrypted = AESUtils.decrypt(key, encrypted);
        System.out.println("Decrypted result: " + decrypted);

        // Verify
        assertEquals(plainText, decrypted, "Encryption and decryption results should be consistent");
        System.out.println("Encryption and decryption consistency: " + plainText.equals(decrypted));
    }

    @Test
    public void testDifferentKeyLengths() {
        String[] keys = {
                "1234567890123456", // 16 bits
                "123456789012345678901234", // 24 bits
                "12345678901234567890123456789012", // 32 bits
                "short", // Short key
                "verylongkeythatwillbetruncatedto32bytes" // Long key
        };

        String plainText = "Test text";

        for (String key : keys) {
            String encrypted = AESUtils.encrypt(key, plainText);
            String decrypted = AESUtils.decrypt(key, encrypted);
            assertEquals(plainText, decrypted, "Key length: " + key.length());
        }
    }

    @Test
    public void testSpecialCharacters() {
        String key = "xiaozhi1234567890";
        String[] testTexts = {
                "Hello World",
                "Hello, Xiaozhi!",
                "Hello, Xiaozhi!@#$%^&*()",
                "Special characters: !@#$%^&*()",
                "Numbers 123 and mixed Chinese",
                "Emoji: 😀🎉🚀",
                "Empty string",
                ""
        };

        for (String text : testTexts) {
            String encrypted = AESUtils.encrypt(key, text);
            String decrypted = AESUtils.decrypt(key, encrypted);
            assertEquals(text, decrypted, "测试文本: " + text);
        }
    }

    @Test
    public void testCrossLanguageCompatibility() {
        // These are the encrypted results generated by the Python version, for testing cross-language compatibility
        String key = "xiaozhi1234567890";
        String plainText = "Hello, Xiaozhi!";

        // Python version generated encrypted results (need to run Python test to get)
        // String pythonEncrypted = "Encrypted results from Python test";
        // String decrypted = AESUtils.decrypt(key, pythonEncrypted);
        // assertEquals(plainText, decrypted, "Java should be able to decrypt the encrypted results of Python");

        // Generate Java encrypted results for Python test
        String javaEncrypted = AESUtils.encrypt(key, plainText);
        System.out.println("Java encrypted results for Python test: " + javaEncrypted);
    }
}